[toolchain]
anchor-version = "0.30.1"
solana-version = "2.0.21"

[features]
seeds = false
skip-lint = false

[programs.localnet]
hackaton = "Cxr1wgQK4EJVMVoiTRJW3ctmHfnrTFiv7iiaSXQJWaaS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/test/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
